# GitHub Labels Configuration
# This file defines all labels for the repository
# Managed by github/issue-label-manager-action

# Priority
- name: "priority: critical"
  color: "d73a4a"
  description: "Critical priority - needs immediate attention"
- name: "priority: high"
  color: "e99695"
  description: "High priority"
- name: "priority: medium"
  color: "f9d0c4"
  description: "Medium priority"
- name: "priority: low"
  color: "fef2c0"
  description: "Low priority"

# Type
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "type: feature"
  color: "0075ca"
  description: "New feature or request"
- name: "type: enhancement"
  color: "a2eeef"
  description: "Enhancement to existing functionality"
- name: "type: documentation"
  color: "0052cc"
  description: "Documentation improvements"
- name: "type: security"
  color: "d73a4a"
  description: "Security-related issue"
- name: "type: performance"
  color: "f9d0c4"
  description: "Performance-related issue"

# Status
- name: "status: in progress"
  color: "fbca04"
  description: "Work in progress"
- name: "status: needs review"
  color: "c5def5"
  description: "Needs code review"
- name: "status: blocked"
  color: "d93f0b"
  description: "Blocked by external factors"
- name: "status: ready"
  color: "0e8a16"
  description: "Ready to be worked on"

# Dependencies
- name: "dependencies"
  color: "0366d6"
  description: "Dependency updates"
- name: "elixir"
  color: "6e4a7e"
  description: "Elixir-related"
- name: "javascript"
  color: "f1e05a"
  description: "JavaScript-related"
- name: "github-actions"
  color: "000000"
  description: "GitHub Actions updates"

# Other
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"