import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :rachel, RachelWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Allow WebSocket connections from custom domain and Fly.io
  check_origin: [
    "https://rachel.stevehill.xyz",
    "https://rachel-game.fly.dev"
  ],
  # Force all traffic to HTTPS in production
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    hsts: true,
    expires: 31_536_000,
    preload: true,
    subdomains: true
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
