name: Assets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test-assets:
    name: Test Assets Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27.0'
        elixir-version: '1.18.0'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache deps
      id: cache-deps
      uses: actions/cache@v4
      env:
        cache-name: cache-elixir-deps
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ env.cache-name }}-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile assets
      run: |
        mix assets.build
        echo "✓ Assets compiled successfully"
    
    - name: Test asset digests
      run: |
        mix phx.digest
        echo "✓ Asset digests generated successfully"
        
    - name: Verify critical assets exist
      run: |
        test -f priv/static/assets/css/app.css || (echo "❌ app.css not found" && exit 1)
        test -f priv/static/assets/js/app.js || (echo "❌ app.js not found" && exit 1)
        echo "✓ All critical assets present"